### ISSUE TITLE
SFX Token doesn't work if it begins with a dash

### ISSUE THREAD

**Issue by mcmiv413** [signalfx/built-in-dashboards#13]
Of course the first token I attempted to use here had a '-' at the beginning and I got this error:

export_dashboards.py: error: argument --key: expected one argument

I expect the issue is that it is not within quoates somewhere within the code. I had tried to put single quotes around it to run as well as trying --key -- -restoftoken and had the same issue.

**Comment by cory-signalfx** [comment]
Hey @mcmiv413! Sorry, I did not have notifications on for this repo and missed your issue. You can fix this by using `--key=-somekeyhere`. The `=` will tell Python's argparse what you want to do. I'll add this to the README.

**Comment by cory-signalfx** [comment]
Done in ab54eb4688bcf1a05567f7dec1dedd84fe22db1a
