### ISSUE TITLE
Unable to use tf code when heatmap is used

### ISSUE THREAD

**Issue by sinagarajan** [signalfx/built-in-dashboards#16]
We use heatmap in our charts .
The code that gets generated don't have the argument 'color' for heatmap alone and terraform throws error because of that, 

    color_range {
        max_value = 0
        min_value = 0
    }

terraform apply output :

 425:     color_range {

The argument "color" is required, but no definition was found.

( Sample  --api_url https://api.us2.signalfx.com --group EVoPCJzA8AA )

**Comment by cory-signalfx** [comment]
This is actually a big in the Terraform provider, so I'll make an issue there too. Thanks @sinagarajan!

**Comment by cory-signalfx** [comment]
[Made the issue here](https://github.com/terraform-providers/terraform-provider-signalfx/issues/195). Was able to reproduce locally.

**Comment by cory-signalfx** [comment]
Hey @sinagarajan, in a few hours Hashi will have released a new version of the provider (4.19.4) in which a fix for this is contained. Should be good to go if using that provider.
